### ISSUE TITLE
Phoenix Cookbook Roadmap

### ISSUE THREAD

**Issue by malkoG** [phoenix-cookbook/phoenix-cookbook.github.io#2]
독학/스터디 교재로 활용하기 무난한 튜토리얼이 되는 것을 목표로 합니다.

# 꼭 넣고 싶은 것

* [ ] Model에 대한 설명 (with Ecto)
* [ ] OneToOne, OneToMany, ManyToOne, ManyToMany
* [ ] Controller/View에 대한 설명
* [ ] CSS 라이브러리 이용하기
* [ ] Context에 대한 설명
* [ ] ExUnit 유닛 테스트
* [ ] ExUnit 통합 테스트
* [ ] 배포하기 (Heroku를 비롯한 PaaS에 배포하기, Dockerfile로 빌드하기, ...)

# 다루면 좋은 주제

* [ ] WebSocket (Phoenix Channel)
* [ ] Phoenix LiveView
* [ ] SPA (+ JWT 인증)
* [ ] Pagination (Scrivener 라이브러리)
* [ ] Eager Loading

# 합의로 결정해야 하는 것

* [ ] 어조 통일
* [ ] 기여 가이드라인(컨벤션) 정하기
